name: poem
channels:
  - conda-forge
dependencies:
  - matplotlib
  - streamlit
  - cmdstan
  - cmdstanpy
  - arviz
  - pip
  - pip:
      # add pip-only packages here if needed
      # e.g. some-package==1.2.3